name: draft-release

on:
  push:
    branches:
      - "master"

jobs:
  update_release_draft_and_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: drafter
        with:
          config-name: release-drafter/template.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
